# Generated by Django 3.2.8 on 2021-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=50)),
                ('LastName', models.TextField(max_length=50)),
                ('Guardian', models.TextField(max_length=50)),
                ('GuardianMobile', models.TextField(max_length=15)),
                ('PatientEmail', models.TextField(max_length=25)),
                ('GuardianEmail', models.TextField(max_length=25)),
                ('PatientMobile', models.TextField(max_length=15)),
                ('AlterNetMobile', models.TextField(max_length=15)),
                ('PatientProblem', models.TextField(max_length=100)),
                ('DrName', models.TextField(max_length=30)),
                ('CurrentAddress', models.TextField(max_length=70)),
                ('ParmanentAddress', models.TextField(max_length=70)),
            ],
        ),
    ]
