# Generated by Django 3.2.8 on 2021-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='AlterNetMobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patients',
            name='DrName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='FirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Guardian',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='GuardianEmail',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patients',
            name='GuardianMobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patients',
            name='LastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PatientEmail',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PatientMobile',
            field=models.CharField(max_length=15),
        ),
    ]
