# Generated by Django 3.2.8 on 2021-10-18 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211018_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='DateOfAdmit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patients',
            name='DateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
