# Generated by Django 3.2.8 on 2021-10-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
