# Generated by Django 3.2.8 on 2021-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_doctors_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='DrAvatar'),
        ),
    ]
